service: serverless-rest-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
